### ISSUE TITLE
I can still navigate the organizer app as a non-admin

### ISSUE THREAD

**Issue by TheKevJames** [Calligre/attendee-web#111]
Note that I can't actually change anything, at least.

**Comment by StevenLocke** [comment]
I can't come up with a good solution to this. I've been trying to trigger an alert if the user doesn't have admin privileges on every page by placing it in the requireAuth function, but that always triggers at least once, because the first time they log in with Auth0, the API server hasn't had time to respond with our profile for them, so the page renders without being able to tell the user's permissions.

Possible solutions:
  Make every organizer page render something until the AuthService responds with a dispatched "isAdmin" event.  This would require a ton of duplicate code though, and would have to be remembered for every new organizer page that ever exists.
  Make some kind of "Authorization Accepted" page, which can be viewed by everyone, and doesn't allow navigation off of it until the server actually looks up the profile. Feels like a hack, but I think it would work.

@Calligre/frontend Anyone have suggestions? I'm stumped.  I've been working on the `warn-non-admin` branch.
